version: '2'

linters:
  enable:
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - unused
    - cyclop
    - durationcheck
    - dogsled
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - godot
    - gosec
    - prealloc
    - wastedassign
    - staticcheck